# NumPy Library in python

# Import Numpy Library

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr1 = np.array((1,2,3,4,5))
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions of array

In [9]:
arr = np.array(20)
print(arr)
print(type(arr))
print("Dimension of array:",arr.ndim)

20
<class 'numpy.ndarray'>
Dimension of array: 0


# 1 d array

In [15]:
arr = np.array([1,2,3,4,5])
print(arr)
print("Dimension of array:",arr.ndim)

[1 2 3 4 5]
Dimension of array: 1


# 2 d array

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("Dimension of array:",arr.ndim)

[[1 2 3]
 [4 5 6]]
Dimension of array: 2


# 3 d array

In [18]:
arr = np.array([[[1,2,3],[2,3,4]]])
print(arr)
print("Dimension of array:",arr.ndim)

[[[1 2 3]
  [2 3 4]]]
Dimension of array: 3


# Check Number of Dimensions?

In [21]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3],[1,2,3]])
d = np.array([[[1,2,3],[1,2,3]]])

print("Dimension of array of a :",a.ndim)
print("Dimension of array of b :",b.ndim)
print("Dimension of array of c :",c.ndim)
print("Dimension of array of d :",d.ndim)

Dimension of array of a : 0
Dimension of array of b : 1
Dimension of array of c : 2
Dimension of array of d : 3


# indexing of the element

In [22]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print("2nd element on 1st row:",arr[0,1])

2nd element on 1st row: 20


In [26]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print("4th element on 1st row:",arr[1,3])

4th element on 1st row: 80


# 3 d array indexing

In [27]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])
print(arr[0,1,2])

6


In [29]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])
print(arr[0,3,2])

12


In [30]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])
print(arr[0,2,0])

7


# slicing of numpy arrays

In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [4]:
print(arr[::2])

[1 3 5 7]


# Slicing in 2d array

In [7]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [8]:
print(a[0,0:5])

[10 20 30 40 50]


# checking the data type of an array

In [10]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [11]:
arr1 = np.array([[1,2,3,4],["Asghwini","Pune","21","Data analyst"]])
print(arr1.dtype)

<U21


# creating array with a defined data type

In [12]:
arr = np.array([1,2,3,4],dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# create an array wuith data types 4 byte integer

In [14]:
arr = np.array([1,2,3,4],dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# numpy array shape

# print the shape of a 2d array

In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


# joining numpy array

In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [26]:
arr1 = np.array([[10,20,30,40],[1,2,3,4]])
arr2 = np.array([[2,4],[4,5]])
arr =np.concatenate((arr1,arr2), axis=1)
print(arr)

[[10 20 30 40  2  4]
 [ 1  2  3  4  4  5]]


# spliting numpy arrays

# Spliting the array in 3 parts

In [27]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# spliting the array in 4 parts

In [28]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel and flatten

In [31]:
m = np.array([[[1,2,3],[1,2,3]]])
print(m)
print(m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is",n.ndim)

[[[1 2 3]
  [1 2 3]]]
3
[1 2 3 1 2 3]
now the new dimension is 1


In [34]:
c = np.array([[[[1,2,3,4],[4,5,6,7]]]])
print(c)
print(c.ndim)
e = c.flatten()
print(e)
print("now the new dimension is",e.ndim)

[[[[1 2 3 4]
   [4 5 6 7]]]]
4
[1 2 3 4 4 5 6 7]
now the new dimension is 1


# unique function

In [36]:
k = np.array([1,2,3,4,5,6,7,1,2,3,89,6,47])
print(k)
x = np.unique(k)
print(x)

[ 1  2  3  4  5  6  7  1  2  3 89  6 47]
[ 1  2  3  4  5  6  7 47 89]


In [37]:
k = np.array([1,2,3,4,5,6,7,1,2,3,89,6,47])
print(k)
x = np.unique(k,return_index = True)
print(x)

[ 1  2  3  4  5  6  7  1  2  3 89  6 47]
(array([ 1,  2,  3,  4,  5,  6,  7, 47, 89]), array([ 0,  1,  2,  3,  4,  5,  6, 12, 10]))


In [39]:
k = np.array([1,2,3,4,5,6,7,1,2,3,89,6,47])
print(k)
x = np.unique(k,return_index = True,return_counts = True)
print(x)

[ 1  2  3  4  5  6  7  1  2  3 89  6 47]
(array([ 1,  2,  3,  4,  5,  6,  7, 47, 89]), array([ 0,  1,  2,  3,  4,  5,  6, 12, 10]), array([2, 2, 2, 1, 1, 2, 1, 1, 1]))


# delete

In [40]:
a = np.array([13,24,45,67])
d = np.delete(a,[1])
print(d)

[13 45 67]


In [42]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2][50,65,6,7]])
print(x)
m = np.delete(x,1,axis = 0)
print()
print(m)

TypeError: list indices must be integers or slices, not tuple